### PR TITLE
Fix kernel loading on mac

### PR DESCRIPTION
**Pull request by testing-ongithub**
Master currently doesn't run on mac. This fixes that.

### CODE REVIEW

**Comment by sosodev** [comment]
Thanks for the PR @testing-ongithub 

I don't think we should move these files out of the resources directory. We should instead fix the lookup to look in the right spot. We can simply the use the main hd plugin class for the lookup.

**Comment by Mark7625** [comment]
I have a pr that fixes all of this and does correct lookups just need to tidy it up

**Comment by testing-ongithub** [comment]
> Thanks for the PR @testing-ongithub
> 
> I don't think we should move these files out of the resources directory. We should instead fix the lookup to look in the right spot. We can simply the use the main hd plugin class for the lookup.

What do you mean? They're still in the resources directory. They're now just in the resources folder for the class that addIncludes them.
https://github.com/RS117/RLHD/blob/master/src/main/java/rs117/hd/opengl/compute/OpenCLManager.java#L402

**Comment by sosodev** [comment]
Sorry, I must have misread the diff :smile:

**Pull request merged**
