### PR TITLE
(Port from GPU) Reset fbo on ResizableChanged on macOS

### PR DESCRIPTION
**Pull request by testing-ongithub**
Port of https://github.com/runelite/runelite/commit/2e34cbc

All credits go to Adam.

### CODE REVIEW

**Comment by sosodev** [comment]
What's the behavior that this fixes?

**Comment by keyosk** [comment]
It's part of a series of fixes that are related to the stretched mode plugin:

- https://github.com/runelite/runelite/commit/bb43d232bb594c6e062e3342fa7db1b53f594c11
- https://github.com/runelite/runelite/commit/637ee563d622fa187b2e4537ade86979bad1dbc9
- https://github.com/runelite/runelite/commit/2e34cbcbe100db843e64f22da48e7335f459e873

**Comment by sosodev** [comment]
Okay cool. :+1:

**Comment by testing-ongithub** [comment]
keyosk's comment gives good background, but these changes aren't just applicable to stretched mode. Currently, switching resizable modes at all (regardless of the stretched mode plugin status) bugs out the screen until the window size is changed.

For example, here's what happens when I switch from fixed mode to resizable on master (despite appearances, stretched mode is not on in this screenshot):
resized

**Pull request merged**
