### PR TITLE
Wood grain texture to generic fences

### PR DESCRIPTION
**Pull request by j-meds**
Texturing for most generic fences. there might be more that I don't have access to so please expand do this.
Fences3
wooden

Fence2

### CODE REVIEW

**Comment by j-meds** [comment]
https://chisel.weirdgloop.org/moid/object_id.html#980,%20981,%20991,%20992,993,%201007,%201008,%201558,%201559,%201560,%201565,%201566,%201567,%20%209623

List is above.

**Comment by NataIynn** [comment]
That looks really nice. Good job!

**Comment by RS117** [comment]
this looks good, but the texture's license attribution will need to be added to the licenses file in the textures directory

**Comment by j-meds** [comment]
> this looks good, but the texture's license attribution will need to be added to the licenses file in the textures directory

Hmmm I did the grunge and texturing myself. I did pull the wooden lines from a site, but after looking at the site it seems only free standard licenses are provided which does not meet the needs of this plug-in After looking on their terms. I will actually draw this out on paper or digitally and just take a pic and apply it to the texture since I do have the layer files. This way we don't deal with licenses.

**Comment by j-meds** [comment]
@RS117 I made my own texture and updated the license file., let me know if you need more info.

More areas addedhttps://chisel.weirdgloop.org/moid/object_id.html#814,%20980,%20981,%20991,%20992,993,%201007,%201008,%201558,%201559,%201560,1561,1562,1563,1564,%201565,%201566,%201567,%201739,%201740,%205432,%205433,5434,5435,5436,5437,%205438,%207055,7527,%209511,%209623

texture2

**Comment by NataIynn** [comment]
Can I ask a question? How hard would this technique be for character models, if possible?

**Comment by j-meds** [comment]
> Can I ask a question? How hard would this technique be for character models, if possible?

Sure. this technique is straightforward since the texture is applied on all the polygons in the model. I think that won't be easy since we can't specify areas in a model, for example a character has different texture in clothing, skin, or other features. In the future we might have application of texture based on Hue ranges, although I'm in very early stages of research. What were you thinking of as an example?

**Comment by NataIynn** [comment]
Just something like this, So it's not as plain.
image
Custom Styles would be better instead exact copy, but staying within OSRS style.

**Comment by j-meds** [comment]
> Just something like this, So it's not as plain.
> image
> Custom Styles would be better instead exact copy, but staying within OSRS style.

Yea actually this is something that would be possible. We'd just need an ItemProperties Object where we can apply texture to anything with an ItemId, in this case do all armors. RS3 HD applied grungy texture to mostly everything even to give it more texture and HD effect. We can just have a list of armors and apply the "Material.GRUNGE_1" to all those Ids and boom we have the texture effect like rs3. 

Maybe this weekend I can look into it.. If there's time.

**Comment by FlenarnTemp** [comment]
While RS3 (And the HD update that came to RS2) did apply a small set of grunge textures to a huge array of objects, it's worth nothing that the setup there was far more customizable than a singular texture applied to any given polygon.

A far better, long-term setup, would be a custom made model-viewer for OSRS models, loaded through cache, that allows one to effectively texture models with the same options and customizability as RS2 did, and from that export out the texture data and load, but as said, that would be far down the road, but might be worthwhile pursuing as this technique only goes so far, and has it's fair share of limitations.

**Comment by Haz4rdz** [comment]
> While RS3 (And the HD update that came to RS2) did apply a small set of grunge textures to a huge array of objects, it's worth nothing that the setup there was far more customizable than a singular texture applied to any given polygon.
> 
> A far better, long-term setup, would be a custom made model-viewer for OSRS models, loaded through cache, that allows one to effectively texture models with the same options and customizability as RS2 did, and from that export out the texture data and load, but as said, that would be far down the road, but might be worthwhile pursuing as this technique only goes so far, and has it's fair share of limitations.

The guys from HDOS have a tool similar to what you proposed. Not sure what the texturing capabilities are, or if it’s compatible with this project.

https://media.discordapp.net/attachments/814525518274887722/857729081897910302/4j5fhl9bdN.mp4

https://youtu.be/zg2Emy4fUuY

**Comment by j-meds** [comment]
> While RS3 (And the HD update that came to RS2) did apply a small set of grunge textures to a huge array of objects, it's worth nothing that the setup there was far more customizable than a singular texture applied to any given polygon.
> 
> A far better, long-term setup, would be a custom made model-viewer for OSRS models, loaded through cache, that allows one to effectively texture models with the same options and customizability as RS2 did, and from that export out the texture data and load, but as said, that would be far down the road, but might be worthwhile pursuing as this technique only goes so far, and has it's fair share of limitations.

This would be optimal since I do want a way to apply textures on walls like that which have wood outside and stone inside. 

image


Applying an all around grunge texturing to some equipment so all around seems like the fastest way to go. I was working on applying multiple textures to similar models by Hue but I don't have the time to really commit. Would your recommendation require me to export the model or have me go into a 3d modeling software? I would not want to need to open up a 3d software for applying custom texturing. I would want to use runelite to know this information, and I personally want it done through configs and hot reload.

Below your recommendation would come in handy since all we can apply multiple textures here.

image

**Comment by FlenarnTemp** [comment]
Easiest way would probably be to build a custom software to handle it, as far as export and hotreload, could possibly be implemented, but incorporating the entire operation into Runelite don't seem feasible really, it's too big of a operation.

You'd need a way to setup how to handle different implementations of the same texture, as RS2 did do it that way to save on texture loading and get more variety out of one single texture. To assign textures and their implementations one would need to to be able to select polygons and visualize the result prior exporting out the result.

As far as what HDOS does @Haz4rdz - they use what I believe is a tool based on a RSPS tool to texture custom models and swap models cache side as their client is a 2009 era client made to work with the current OSRS systems.

**Comment by j-meds** [comment]
> Easiest way would probably be to build a custom software to handle it, as far as export and hotreload, could possibly be implemented, but incorporating the entire operation into Runelite don't seem feasible really, it's too big of a operation.
> 
> You'd need a way to setup how to handle different implementations of the same texture, as RS2 did do it that way to save on texture loading and get more variety out of one single texture. To assign textures and their implementations one would need to to be able to select polygons and visualize the result prior exporting out the result.
> 
> As far as what HDOS does @Haz4rdz - they use what I believe is a tool based on a RSPS tool to texture custom models and swap models cache side as their client is a 2009 era client made to work with the current OSRS systems.

Yea researching rsps tools provided me with that knowledge. Somebody in the forum did actually connect 2008 HD client to osrs servers which is practically HDOS. I really like the art style this is providing instead of the grungified all over 2008 era graphics.

Hmmm I'm wondering if RL could just highlight polygons and provide that information when you are in --developer mode. Overall it seems like a lot of work going into each polygon and doing this, I would think this would only apply to bosses or npcs people like.

 What do you think application of texture based on Hue ranges? It would actually allow me to apply specific textures based on a range. We could keep the same texturing config we have now and be able to apply 2-3 textures depending on its range. Just seems easier on my opinion,  Example: you have this wall so you want to apply a wooden texture on the darker wood color  outside and inside there is a stone wall with a wooden seam. The wooden outside and inside wooden beam would get the wood texture, then the white stone part would get a stone texture. By far much faster implementation and to add quick textures based on my experience.

**Comment by j-meds** [comment]
@FlenarnTemp 
For example in new cannon design, I'll apply armor metal grunge texture for the dark gray color and for the brown color wood I'll apply a wooden texture. could be as simple as using our same config.
image

**Comment by NataIynn** [comment]
What about procedural texturing? Then you can have many different styles with just code.

**Pull request merged**
