### PR TITLE
Bump gradle version to 7.4

### PR DESCRIPTION
**Pull request by testing-ongithub**
For three reasons:

1. for consistency with https://github.com/runelite/example-plugin/commit/dc2102c
2. to allow the plugin to build with JDK 17
3. to make it so I don't need to keep making this change locally whenever I make/pull a new branch

Reasons 2 and 3 go together. I hadn't noticed Reason 1 until now, which is why I didn't make this PR earlier. 😅

### CODE REVIEW

**Comment by sosodev** [comment]
Are you sure that's the right gradle-wrapper jar? The wrapper jar from the 7.4 distribution zip has a different sha256

**Comment by aHooder** [comment]
Checks out with the hash for v7.4.2 displayed [here](https://gradle.org/release-checksums/) on my end

**Comment by sosodev** [comment]
Indeed it does :+1: I guess the one in the distribution zip is just slightly different for whatever reason

**Comment by aHooder** [comment]
Yeah, who knows why :shrug:. I'm happy to see that you're checking this sort of thing :slightly_smiling_face:

**Comment by Mark7625** [comment]
> Indeed it does 👍 I guess the one in the distribution zip is just slightly different for whatever reason

Sometimes Intellij Caches it and u have to revalidate your caches and reload, I had the issue a few times on other Projects

**Pull request merged**
