### PR TITLE
GOTR

### PR DESCRIPTION
**Pull request by xxEzri**
Basic dynamic lights and environment for Guardians of the Rift minigame. Lots of room for polish but it's much prettier than defaults already!

### CODE REVIEW

**Comment by xxEzri** [comment]
Proper comparison image (live 117hd vs new environment with same settings)

https://cdn.knightlab.com/libs/juxtapose/latest/embed/index.html?uid=8c935cee-ab73-11ec-b5bb-6595d9b17862

**Comment by xxEzri** [comment]
Fog makes the background look better but the abyssal area look pretty bad IMO - might be able to tweak lighting over there so that it shines through better. The abyssal portal is right on the edge of the scene so it gets eaten by even a few clicks of fog.

**Comment by xxEzri** [comment]
Standardised a few names and added a light for the temporary portals

**Comment by xxEzri** [comment]
Added a few more changes, color space fix and a refinement pass over many of the values. Thanks to @aHooder for helping with the color space details as always 👍

**Comment by Mark7625** [comment]
Looks good, I think we should add caustics  that @sosodev Was talking about it it would make the underwater effect seem much more real

**Comment by xxEzri** [comment]
> Looks good, I think we should add caustics that @sosodev Was talking about it it would make the underwater effect seem much more real

Bit tricky because i think the gameplay area is not supposed to be actually underwater, just in an area which is below ocean. More fog also looks much more underwatery but it starts to come into the gameplay area and to make it more difficult to play the game.

w/ @aHooder we've added a light ID for the abyssal portal and after some investigation, the fog issue mostly applies when people log in or enter the lobby and then look at the area without going into the minigame itself. If you go into the minigame you can load a further 4-8 tiles and that makes the portal area look quite a bit better.

image

**Comment by xxEzri** [comment]
https://streamable.com/9gvtkn

With #269, #270

also:
.setAmbientStrength(0.7f)
.setDirectionalStrength(0.35f)

**Pull request merged**
