### PR TITLE
Add Yanille orb & portal lighting

### PR DESCRIPTION
**Pull request by kinztechcom**
This PR adds lighting to orbs in Yanille specifically the orbs at Nightmare zone, outside of the magic guild, and on the third floor of the magic guild. It also adds it to the three portals on the third floor of the magic guild.

https://gyazo.com/8454d044ef72bf0acdd859ddc4c5733e
https://gyazo.com/429f4085494e1c45d301ef9ccd4fccc9
https://gyazo.com/322fee03b4fa415100a35535b288b1e0

Note that the issue with the shadows is already mentioned #56 but not addressed here.

### CODE REVIEW

**Comment by NataIynn** [comment]
The wizard tower lighting height may need to adjusted more. They seem a bit too low and not in the correct place?

**Comment by stevenwaterman** [comment]
Does this also fix the powerup orbs inside the nightmare zone?

**Comment by AustinGarrettR** [comment]
Just weighing in, that In my opinion the flashing/intensity of these lights is too strong. It would be better if more subtle.

**Comment by kinztechcom** [comment]
> Just weighing in, that In my opinion the flashing/intensity of these lights is too strong. It would be better if more subtle.

I agree, they were a little too flashy.

More subtle:
https://gyazo.com/8b938336fe7d53e0688bb1c579b78207
https://gyazo.com/d8b41dfdd065008ea9ddc5e7975fc182
https://gyazo.com/23d663abb61dc8a484260b112e8f066f

**Pull request merged**
