### PR TITLE
Sky color

### PR DESCRIPTION
**Pull request by Mark7625**
image

This has been fixed, I have added a Enum to override the sky color when you within a certain area. This needed to be changed as some places do this an effect.

### CODE REVIEW

**Comment by sosodev** [comment]
This duplicates the existing area override functionality. 

As it stands we can define an area https://github.com/RS117/RLHD/blob/master/src/main/java/rs117/hd/environments/Area.java
And then a custom environment for that area https://github.com/RS117/RLHD/blob/master/src/main/java/rs117/hd/environments/Environment.java

I believe you can use these tools to accomplish the same thing here :slightly_smiling_face:

**Review by sosodev — CHANGES_REQUESTED** [review]
This duplicates the existing area override functionality.

As it stands we can define an area https://github.com/RS117/RLHD/blob/master/src/main/java/rs117/hd/environments/Area.java
And then a custom environment for that area https://github.com/RS117/RLHD/blob/master/src/main/java/rs117/hd/environments/Environment.java

I believe you can use these tools to accomplish the same thing here :slightly_smiling_face:

**Comment by Mark7625** [comment]
> This duplicates the existing area override functionality.
> 
> As it stands we can define an area https://github.com/RS117/RLHD/blob/master/src/main/java/rs117/hd/environments/Area.java And then a custom environment for that area https://github.com/RS117/RLHD/blob/master/src/main/java/rs117/hd/environments/Environment.java
> 
> I believe you can use these tools to accomplish the same thing here 🙂

As for the Environment you can only set a fog color not a sky color this does not have the same effect

**Comment by sosodev** [comment]
> As for the Environment you can only set a fog color not a sky color this does not have the same effect

They're functionally the same thing at the moment. 

Here's fog enabled and disabled. The sky color just inherits from the fog color.

disabled
enabled

**Pull request closed without merging**
