### PR TITLE
Baked lights Changes

### PR DESCRIPTION
**Pull request by Mark7625**
Added A baked Light id and Magic Carpet Fix

### CODE REVIEW

**Comment by sosodev** [comment]
We don't need to copy the item ID definitions here because they're only needed at compile time

**Comment by Mark7625** [comment]
> We don't need to copy the item ID definitions here because they're only needed at compile time

We need them for compile time tho? Since they are used for carpets?

**Comment by sosodev** [comment]
The compiler will substitute `ItemID.MAGIC_CARPET` with the actual ID during compilation. We needed to copy the other IDs so we could lookup the IDs for the enum values that we have in the JSON at runtime.

**Comment by Mark7625** [comment]
Ah didn't think it did that, fair enough I'll remove it now

**Pull request merged**
