### PR TITLE
Add tile info overlay for development

### PR DESCRIPTION
**Pull request by aHooder**
Adds the following overlay to help with modifying tile overlays, underlays and materials. Currently it's toggled by the hard-coded keybind Ctrl F3, and it only works while in developer mode.

image

image

image

This also restricts shader hot-swapping to developer mode.

### CODE REVIEW

**Comment by Mark7625** [comment]
Love u

**Comment by aHooder** [comment]
This should be good to go now :+1: 

image

**Comment by sosodev** [comment]
Could we break the key listener bits out into its own class?

**Comment by aHooder** [comment]
That'd be fine with me. Do you have anything in particular in mind? Maybe a devtools class?

**Comment by sosodev** [comment]
No idea in particular. I'd just like to keep trying to slim down what functionality we put into the main HD plugin class.

**Comment by aHooder** [comment]
Sounds good. I suppose in the future we'll inevitably add more dev tools, so it might be good to move logic for managing that to a separate class.

**Comment by Mark7625** [comment]
> Sounds good. I suppose in the future we'll inevitably add more dev tools, so it might be good to move logic for managing that to a separate class.

I do have a hotkey class in my dev panel thing maybe can just go into that one it's in

**Comment by aHooder** [comment]
I've moved both shader hotswapping and tile info into a separate class for managing devtools. On second thought though, should we perhaps keep shader hotswapping for non-developers in case we want to try fixing shader bugs through the support channel?

**Comment by Mark7625** [comment]
> I've moved both shader hotswapping and tile info into a separate class for managing devtools. On second thought though, should we perhaps keep shader hotswapping for non-developers in case we want to try fixing shader bugs through the support channel?

Not sure how I feel about that what if we add a enable debug in config Panel off by default ?

**Pull request merged**
