### PR TITLE
Add ObjectLight data for Blast Furnace melting pot

### PR DESCRIPTION
**Pull request by keyosk**
This adds a nice warm glow to the blast furnace room

image

image

### CODE REVIEW

**Comment by judz5** [comment]
The lighting seems too low to me, almost like its coming from the middle of the pot.

**Comment by j-meds** [comment]
The lighting is low but I also don't see any on the ground.

**Comment by keyosk** [comment]
> The lighting seems too low to me, almost like its coming from the middle of the pot.

How's this?

image

```diff
diff --git a/src/main/java/rs117/hd/lighting/ObjectLight.java b/src/main/java/rs117/hd/lighting/ObjectLight.java
index ae06d15..09fa6bd 100644
--- a/src/main/java/rs117/hd/lighting/ObjectLight.java
+++ b/src/main/java/rs117/hd/lighting/ObjectLight.java
@@ -354,7 +354,7 @@ enum ObjectLight
 	DORGESHKAAN_THINGYMAJIG(150, Alignment.CENTER, 500, 6f, rgb(50, 10, 255), LightType.FLICKER, 0, 20, THINGYMAJIG),
 
 	// Blast Furnace
-	BLAST_FURNACE_MELTING_POT(50, Alignment.CENTER, 1200, 10f, rgb(252, 122, 3), LightType.FLICKER, 0, 20, MELTING_POT),
+	BLAST_FURNACE_MELTING_POT(300, Alignment.CENTER, 1200, 10f, rgb(252, 122, 3), LightType.FLICKER, 0, 20, MELTING_POT),
 
 	// Misc
 	// This is a generic portal reused in different locations. It's identical to the private corp portal
```

**Comment by j-meds** [comment]
Looks good and the higher brightness added some life to the furnance.

**Pull request merged**
