### PR TITLE
Add caustics to underwater environments

### PR DESCRIPTION
**Pull request by aHooder**
<details>
  <summary>Outdated previews</summary>

  https://user-images.githubusercontent.com/831317/160238535-a5e6a8e7-8b58-4826-91ae-bb598af60b8f.mp4

  https://user-images.githubusercontent.com/831317/160238540-82c44ae7-e520-446a-ba62-cd1bf065f60e.mp4

  New area with #267 
  https://user-images.githubusercontent.com/831317/160238920-fa0903d6-a029-426b-bc12-b899f6de9a7a.mp4
</details>

Maybe the effect could use a bit more tinkering, but I think it looks decent.

The texture is taken from [this lovely website](https://opengameart.org/content/water-caustics-effect-small) and is licensed under CC0.

### CODE REVIEW

**Comment by aHooder** [comment]
This now works properly for different heights and with shadows, and looks a bit nicer. Not as subtle as before. Still not 100% happy with it, but it's getting there.

https://user-images.githubusercontent.com/831317/160254989-2a8c1303-c9df-4cd1-ad0a-91933a8747a1.mp4

https://user-images.githubusercontent.com/831317/160254992-2269f141-dbdf-4993-aefe-7c6c1e2289c1.mp4

https://user-images.githubusercontent.com/831317/160254991-957553c8-0688-4af0-bbe2-f7a511446aad.mp4

@xxEzri's changes to Temple of the Eye are not included in this PR, but can be [tested with caustics here](/ahooder/RLHD/tree/gotr-caustics-testing).

**Comment by xxEzri** [comment]
https://streamable.com/9gvtkn

#267, #269, #270

also:
.setAmbientStrength(0.7f)
.setDirectionalStrength(0.35f)

I prefer these values

**Comment by aHooder** [comment]
I've added config options to toggle the underwater effects, and caustics to the overworld as well. The old caustics are still used when water effects are set to "subtle". Here's a few previews:

https://user-images.githubusercontent.com/831317/160282659-cd0bb73c-6c70-4274-83f9-35b6ea7d1b44.mp4

https://user-images.githubusercontent.com/831317/160282772-81aa7fbe-919a-47a4-b533-3f74fe66ab05.mp4

**Comment by aHooder** [comment]
Forgot to mention, I subtly changed how the caustics were applied. Now it's multiplicative but done right, so it looks more realistic. Here's what Fossil Island looks like currently:

https://user-images.githubusercontent.com/831317/160283160-467fb371-ae84-40e7-ba93-8e1f4350dd5c.mp4

**Comment by RS117** [comment]
I would be fine with removing the old caustics effect entirely as this one looks and works much better. And a slight tangent, but I'm also thinking about getting rid of the 'water effects' setting entirely as I don't think anyone uses the 'simple' setting..

**Comment by aHooder** [comment]
Should I go ahead and remove the config option for water effects in this PR?

**Comment by RS117** [comment]
I figure it's probably worth doing all at once as it's all so closely intertwined, but if you'd prefer I can merge this as-is and remove the setting in a separate commit tomorrow

**Comment by aHooder** [comment]
Sounds good to me :+1: I've gone ahead and replaced the Water Effects option with Underwater Caustics, and instead tied both regular and environmental caustics to the same config option. Let me know if you want these to be separate still.

**Comment by aHooder** [comment]
Forgot to replace the old texture :sweat_smile:

**Comment by aHooder** [comment]
Any objections to me squashing these commits? I think the PR is pretty much good to go.

**Comment by AustinGarrettR** [comment]
Just my opinion, the latest preview looks awesome, but just a tad too intense. I'd reduce the intensity of the effect by 20-30%. 

And optionally if you really wanted to take it to the next level, you could add an additional large scale noise mask, to break it up. Typically water has waves on the surface, so you might find the caustics warping under large waves, or having lower brightness under a large wave as it moves across. This might be way too much effort though.

Excellent PR!

**Comment by aHooder** [comment]
How about this? 20 is the default brightness btw

https://user-images.githubusercontent.com/831317/165901786-061b39f4-6a85-48ae-aac9-2e172341371b.mp4

https://user-images.githubusercontent.com/831317/165901798-fc6cbeae-0224-4c73-93ec-3f37b15ff4bf.mp4

**Comment by AustinGarrettR** [comment]
> How about this? 20 is the default brightness btw
> 
>  underwater.mp4 
>  surface.mp4

Looks perfect to me.

**Comment by aHooder** [comment]
I'm experimenting with some more stuff. Any thoughts on these?

https://user-images.githubusercontent.com/831317/165940704-10ef26b5-5b6f-488f-9867-d8dc0bbcf62b.mp4

https://user-images.githubusercontent.com/831317/165940662-0b1a82af-791a-4faf-9def-1203e848914f.mp4

https://user-images.githubusercontent.com/831317/165941260-095e5a9e-ed67-467a-9e54-867e051d161c.mp4

https://user-images.githubusercontent.com/831317/165941268-45709847-e1ad-48b7-9863-6be28f84941c.mp4

**Comment by xxEzri** [comment]
IMO

Darkening is okay but too strong
Hate CA
Drift looks great but is too fast

**Pull request merged**
