### PR TITLE
Changed tile recolouring to only occur when Ground Textures are enabled

### LINKED ISSUE #158: Plugin still applying tile recolouring with ground textures disabled.
**Describe the bug**
Tile recolouring is still applied with ground textures disabled. This is most noticeable in Edgeville where a large amount of new paths have been created.

**To Reproduce**
1. Go to Edgeville
2. Disable "Ground Textures"
3. Toggle between 117 HD and GPU plugins
4. Notice the difference in tile colours

**Expected behavior**
With the ground textures disabled, ground tiles should show their default vanilla colours. Tile recolouring should only happen when ground textures are enabled.

**Screenshots**

Ground Textures and blending enabled - a very nice HD path
Ground Textures and blending enabled

Ground Textures and blending disabled - unexpected tile recolouring
Ground Textures and blending disabled

117 HD disabled - default tile colours
117 HD disabled

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.7.25
 - Launcher version: 2.0.2
 - 117 HD version: 1.0.5

### PR DESCRIPTION
**Pull request by yungando**
Tiles will no longer be recoloured if Ground Textures are disabled, will use their default colour instead. Closes #158.

Also fixes new issue in 1.0.7 with unexpected tile recolouring when Ground Blending is disabled, as shown in https://github.com/RS117/RLHD/issues/158#issuecomment-954337892.

Ground Textures & Ground Blending Disabled

Ground Blending only

Ground Textures only

Ground Blending & Ground Blending enabled

### CODE REVIEW

**Comment by RS117** [comment]
I think it would make more sense to use `hdPlugin.configGroundBlending` instead of `hdPlugin.configGroundTextures` in `ProceduralGenerator` so that the recolors are still applied with textureless ground blending. otherwise, it looks good

**Comment by yungando** [comment]
The colours generated by `ProceduralGenerator` are only used when `hdPlugin.configGroundBlending` is enabled, so just removing the `hdPlugin.configGroundTextures` check would have the effect you want.

**Comment by yungando** [comment]
Tested with the new change and recolours are still applied with textureless groundblending, should be good to go.

**Comment by RS117** [comment]
great! thank you

**Pull request merged**
