### PR TITLE
draw loading and connection lost boxes

### PR DESCRIPTION
**Pull request by sosodev**
This reintroduces https://github.com/runelite/runelite/commit/6f5735be077e74e3790b9163bcf8d2684eedbb00

But with the logic fixed so that shadows can be drawn while the loading is happening as well. I believe this also fixes the screen flickering that some users have reported during loading. https://github.com/RS117/RLHD/issues/199 in particular seems to be fixed by these changes.

### CODE REVIEW

**Comment by sosodev** [comment]
Actually the shadow drawing is a little inconsistent but it's passable I think

**Comment by xxEzri** [comment]
Shadows do not draw with everything else for a fraction of a second before teleporting away from a scene

**Comment by xxEzri** [comment]
Also when loading new areas via running

There is ~1 tick of everything being rendered without shadows before the loading pause which leaves it on screen for a longer period of time (~100ms).

**Comment by aHooder** [comment]
I've pushed a couple additional small commits to my [branch](https://github.com/aHooder/RLHD/commits/fix-loading-draw). One to fix an issue with incorrect offsets while loading in fixed mode (4-pixel gaps), and the other to bring the scene render condition back in line with the regular GPU plugin, just in case rendering in unknown states could cause problems.

**Comment by sosodev** [comment]
Thanks @aHooder for your fixes. The loading is very consistent now so I've merged your changes in. :)

**Pull request merged**
